# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  branch: master

# These lines should *not* be indented
media_folder: "src/assets"
public_folder: "/assets"

# These lines should *not* be indented
collections:
  - label: "Content"
    name: "content"
    files:
      - label: "Data"
        name: "data"
        file: "src/content/data.json"
        fields:
          - label: "About"
            name: "about"
            widget: object
            summary: '{{fields.name}}'
            collapsed: true
            fields:
              - {label: Name, name: name, widget: string, required: true}
              - {label: Avatar, name: avatar, widget: image, required: false}
              - {label: Title, name: title, widget: string, required: false}
              - {label: About, name: about, widget: string, required: false}
              - {label: Link, name: link, widget: string, required: false}

          - label: "Experience"
            name: "experience"
            widget: list
            fields: &card_fields
              - {label: Side, name: side, widget: string, required: true}
              - {label: Title, name: title, widget: string, required: true}
              - {label: Desc, name: desc, widget: string, required: false}
              - {label: Stack, name: stack, widget: string, required: false}
              - {label: Image, name: image, widget: image, required: false}
              - {label: Link, name: link, widget: string, required: false}
              - {label: Source, name: source, widget: string, required: false}

          - label: "Projects"
            name: "projects"
            widget: list
            fields: *card_fields

          - label: "Links"
            name: "links"
            widget: list
            fields: *card_fields