# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  branch: master

# These lines should *not* be indented
media_folder: "src/assets"
public_folder: "/assets"

# These lines should *not* be indented
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "src/content/about.json"
        fields:
          - {label: Name, name: name, widget: string, required: true}
          - {label: Avatar, name: avatar, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: About, name: about, widget: string}
          - {label: Link, name: link, widget: string}

      - label: "Experience"
        name: "experience"
        file: "src/content/experience.json"
        widget: list
        fields: &card_fields
          - {label: Side, name: side, widget: string, required: true}
          - {label: Title, name: title, widget: string, required: true}
          - {label: Desc, name: desc, widget: string}
          - {label: Stack, name: stack, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Link, name: link, widget: string}
          - {label: Source, name: source, widget: string}

      - label: "Projects"
        name: "projects"
        file: "src/content/projects.json"
        widget: list
        fields: *card_fields

      - label: "Links"
        name: "links"
        file: "src/content/links.json"
        widget: list
        fields: *card_fields