# when using the default proxy server port
backend:
  name: git-gateway
  branch: master

# These lines should *not* be indented
media_folder: "public/assets"
public_folder: "assets"

site_url: https://amitabhsahu.dev
display_url: https://amitabhsahu.dev

# These lines should *not* be indented
collections:
  - label: "Content"
    name: "content"
    files:
      - label: "Data"
        name: "data"
        file: "src/content/data.json"
        fields:
          - label: "Profile"
            name: "profile"
            widget: object
            fields:
              - {label: Name, name: name, widget: string, required: true}
              - {label: Resume, name: resume, widget: file, required: true, allow_multiple: false, choose_url: false, media_library: {config: {track: "*.pdf"}}}
              - {label: Avatar, name: avatar, widget: image, required: false, allow_multiple: false, choose_url: false, media_library: {config: {track: "*.webp"}}}
              - {label: Title, name: title, widget: string, required: false}
              - {label: About, name: about, widget: string, required: false}

          - label: "Experience"
            name: "experience"
            widget: list
            add_to_top: true
            fields: &card_fields
              - {label: Side, name: side, widget: string, required: true}
              - {label: Title, name: title, widget: string, required: true}
              - {label: Desc, name: desc, widget: string, required: false}
              - {label: Stack, name: stack, widget: string, required: false}
              - {label: Image, name: image, widget: image, required: false, allow_multiple: false, choose_url: false, media_library: {config: {track: "*.webp"}}}
              - {label: Link, name: link, widget: string, required: false}

          - label: "Projects"
            name: "projects"
            widget: list
            add_to_top: true
            fields: *card_fields

          - label: "Links"
            name: "links"
            widget: list
            add_to_top: true
            fields: *card_fields